// 内置备注数据 —— 仅首次安装时种入 chrome.storage,之后以 storage 为准
// key 保留 @ 前缀,查找时大小写不敏感
var XR_DEFAULT_REMARKS = {
  "@020210jh": "畜生开盘割人",
  "@0xCryptoUni": "撸毛-任务型博主",
  "@0xEMC2WIN": "咋咋呼呼，不知真的赚钱否",
  "@0xJ818": "暴力杠杆交易员",
  "@0xJoeMov": "狗骗子",
  "@0xLuo": "Base链研究",
  "@0xMustardz": "畜生开盘割人",
  "@0xSleepinRain": "睡裙群主",
  "@0xSleuth_": "英文区影响力KOL",
  "@0xTaiBai": "交易玩家-收费",
  "@0x_CryptoAu": "Base链研究",
  "@0xbor": "kolscan创始人",
  "@0xdetweiler": "机器人赛道研究",
  "@0xfanfanfan": "畜生开盘割人",
  "@0xfengxun": "新币玩家",
  "@0xlong_life": "SOL&ICM",
  "@9yointern": "Jup 项目方",
  "@AI_BRK": "AIBRK Tech Lead",
  "@AndreCronjeTech": "AC Sonic创始人 口碑一般 DeFi元老",
  "@AveryChing": "APT CEO",
  "@Barret_China": "阿里开发",
  "@ChillHouseSOL": "Chillhouse法国销售代表",
  "@ClairvoyantLabs": "持续关注",
  "@CryptoCaligh": "挖坟贴老手，也许是跳大神",
  "@CryptoCapo_": "英文社区著名反指",
  "@Crypto_Cat888": "热点短平快交易",
  "@Cryptobaofu": "避而远之",
  "@CyptoForest": "meme玩家-研究型",
  "@Darkfarms1": "Bome作者",
  "@DexterOnchain": "工具叼毛",
  "@DigitsCapital": "英文区影响力KOL",
  "@Domingo_gou": "避而远之",
  "@DontShelll": "国内打狗kol",
  "@DoveyWan": "诈骗犯的何一闺蜜",
  "@Eason5825": "宝藏投研型博主",
  "@ForrestOLAB": "诈骗犯项目",
  "@Ga__ke": "尼玛DNF",
  "@GeoffreyHuntley": "RALPH畜生开发者",
  "@HeetTike": "Noice",
  "@IncomeSharks": "股票和加密货币分析与预测",
  "@JUST_DO_ITS7": "Bonk冲狗",
  "@JackDishman": "Clanker DEV",
  "@Kawasakitesu": "看起来也是装逼的",
  "@KelseyWeb3VC": "二级交易 & 趋势",
  "@Kong408": "Creator合伙人",
  "@LongzuAlpha": "打狗",
  "@MLeeJr": "LFI创始人",
  "@MaWanShuooo": "Base链研究",
  "@Master_Jobber": "老骗子",
  "@McCain889": "避而远之",
  "@MichaelHirsch": "SLOP Dev",
  "@MichaelandMa": "Creator创世人 | 甩手掌柜？",
  "@Murphychen888": "数据“分析师”",
  "@Neon2089": "投研搞起",
  "@NousResearch": "Hermes创始人",
  "@PayAINetwork": "x402",
  "@RicardoBitget": "畜生开盘割人",
  "@SemiAnalysis_": "专门拆解 英伟达 美光HBM GPU",
  "@Shawred0": "AI相关研究",
  "@SolportTom": "Bonk创始人",
  "@StaniKulechov": "AAVE 创始人",
  "@StriderOnBase": "有点意思的Alpha",
  "@TheRyo_778": "投研",
  "@VitalikButerin": "ETH创始人",
  "@WeSn0w": "高质量分析？",
  "@YA971718": "避而远之",
  "@Y_babyshow": "Base链投研",
  "@YanLiberman": "有趣的观点",
  "@ZephyrTrading": "畜生开盘割人",
  "@_johngranata": "Base 产品？",
  "@_jsmth": "Believe App工程师",
  "@a1lon9": "PUMP CEO ctm",
  "@aeyakovenko": "Solana创始人",
  "@aleabitoreddit": "新股神？？？还是跳大神",
  "@andy8052": "区块链开发者、加密货币爱好者",
  "@blknoiz06": "黑鬼",
  "@brian_armstrong": "Base CEO",
  "@btcbabycow": "Alpha挖掘- Base",
  "@btcxiage": "诈骗犯",
  "@cb_doge": "马斯克狗腿子",
  "@chickenBrother_": "技术 ｜ 分析师",
  "@clankeronbase": "Clank儿",
  "@corbits_dev": "x402 框架",
  "@crypto_popseye": "英文区影响力KOL",
  "@cryptok64440829": "避而远之",
  "@cryptoxiao1127": "感谢6551",
  "@cz_binance": "赵长鹏",
  "@d33v33d0": "西红柿开发者",
  "@danielesesta": "Sonic链Anon Dev",
  "@daosdotfun": "初代发币模式 DAO",
  "@defidude": "crypto 老玩家  Ratspeak 开发和推广",
  "@diiorioanthony": "以太坊联合创始人",
  "@elonmusk": "马斯克",
  "@feltanimalworld": "AI相关",
  "@fundstrat": "Tom Lee 华尔街大佬",
  "@game_for_one": "Alpha信号KOL",
  "@gammichan": "外国KOL 研究型",
  "@gengdaJ": "AI相关工具研究",
  "@goocarlos": "Dify CEO",
  "@higgsfield_ai": "AI视频合成网站",
  "@himgajria": "小心！大割",
  "@hubzify": "避而远之",
  "@hunterweb303": "Web3开发",
  "@iamkadense": "Bonk核心贡献者",
  "@infinit49976199": "撸毛",
  "@iruletrenches": "Base Kol 国内人称行业冥灯",
  "@jessepollak": "垃圾杰西",
  "@jimcramer": "英文CT著名反指",
  "@js_horne": "Zora创始人",
  "@jukan05": "研究员？",
  "@jup_studio": "JUP台子",
  "@klik_evm": "EVN 发射台",
  "@kolscan": "PUMP 收购的项目",
  "@kunlunstar": "算命的？还行",
  "@liaoblove520": "避而远之",
  "@lifefind_itsway": "扒链",
  "@maid_crypto": "臭傻逼",
  "@mayangdarana": "畜生开盘割人",
  "@metaplex": "SOL上的发射&投融",
  "@missoralways": "$memecoin最早喊单的核心人物 英文区KOL",
  "@mrpapawheelie": "Base生态分析",
  "@nanbeiblock": "交易&投研&Alpha",
  "@nftsiy": "避而远之",
  "@notthreadguy": "人工智能|兼职主播",
  "@novogratz": "sol链“Tom lee”",
  "@opinionlabsxyz": "诈骗犯项目",
  "@pasternak": "Believe创始人",
  "@poe_real69": "老外喊单KOL",
  "@predictionindex": "预测市场聚合站",
  "@qrcoindotfun": "Base链上竞拍广告位",
  "@rbthreek": "英文区 KOL",
  "@runes_leo": "预测市场策略 · AI 工具实战 · 独立构建日常",
  "@ryolu_": "Cursor",
  "@ryzzqq": "值得关注",
  "@sama": "OpenAI奥特曼",
  "@shirleyusy": "庄",
  "@sibeleth": "拿钱办事 国外畜牲",
  "@sidewinder1901": "moonshot营销主管",
  "@spncrk": "ORGO 创始人",
  "@starving_series": "拍短剧的",
  "@stitchdegen": "一级二段博主",
  "@stompymoppybase": "我操，改名了，注意安全",
  "@stventure_": "投研大佬TBD",
  "@supercontraa": "alpha",
  "@thetradingstar": "被CoinbaseAsset关注",
  "@uponlymodee": "应用币版本T0",
  "@waiting027": "投研-Base",
  "@wangyiduo0404": "畜生开盘割人",
  "@web3_home": "避而远之",
  "@x0110GYY": "避而远之",
  "@xhanTululu": "Alpha研究",
  "@xmtp_": "高融资 消息通讯",
  "@yetone": "开发者",
  "@yiboyun613": "装逼博主",
  "@zachxbt": "内幕 装逼狗"
};

if (typeof globalThis !== "undefined") globalThis.XR_DEFAULT_REMARKS = XR_DEFAULT_REMARKS;

/* ============================================================
 * 默认设置 —— 同样只在首次安装时种入,之后以 storage 里的 __settings 为准
 *   noiseMode: off(关闭) | dim(淡化) | collapse(折叠) | hide(隐藏)
 *   rules:     按顺序匹配,第一条命中的生效;match 是关键词数组,大小写不敏感
 *              color 决定药丸颜色,noise 决定这类人的推文算不算噪音
 * ============================================================ */
var XR_DEFAULT_SETTINGS = {
  noiseMode: 'dim',
  dimOpacity: 0.3,
  hideAds: true,
  rules: [
    {
      name: '拉黑',
      color: '#ff3b30',
      noise: true,
      match: ['避而远之', '割人', '骗子', '诈骗', '反指', '大割', '畜生', '小心']
    },
    {
      name: '项目方',
      color: '#8e8e93',
      noise: false,
      match: ['创始人', 'CEO', '项目方', '台子', '合伙人', 'dev', '开发']
    },
    {
      name: '投研',
      color: '#34c759',
      noise: false,
      match: ['投研', '研究', '分析', 'alpha', 'kol', '交易']
    }
  ]
};

if (typeof globalThis !== "undefined") globalThis.XR_DEFAULT_SETTINGS = XR_DEFAULT_SETTINGS;
